public/static/locales/en/common.json

Changed text from "Private" to "Privacy" on cookie banner

---

src/community/connect/EventsData.tsx

events were stuck on loading bc top event was missing. 
now will at least show the events that are there.

show events even if top event or upcomming missing (but not both)

---

src/_page-tests/experience/__snapshots__/color.test.tsx.snap
src/_page-tests/experience/__snapshots__/composition.test.tsx.snap
src/_page-tests/experience/__snapshots__/exchange-icons.test.tsx.snap
src/_page-tests/experience/__snapshots__/icons.test.tsx.snap
src/_page-tests/experience/__snapshots__/index.test.tsx.snap
src/_page-tests/experience/__snapshots__/key-imagery.test.tsx.snap
src/_page-tests/experience/__snapshots__/logo.test.tsx.snap
src/_page-tests/experience/__snapshots__/typography.test.tsx.snap
src/analytics/analytics.ts
src/experience/common/TopBar.tsx

Description
Removed the underline decoration from the navbar kit title.
What is the current behavior, and what is the updated/expected behavior with this PR?
**Before**
**After**
**Test Ran**
Related issues
Fixes #110

Removed the underline decoration from the navbar kit title. 

---

package.json

Mostly replaced `;` for `&&` so that if one step fails the deployment is aborted.

Autofail deploy if build step fails

---

src/celo-rewards/CeloRewardsTerms.tsx

There was a `Each child in a list should have a unique "key" prop.` warning on `CeloRewardsTerms` that this PR fixes.

Fix warning on CeloRewardsTerms

---

README.md

It’s just brew intall google-cloud-sdk

brew cask is outdated.

---

public/static/locales/en/home.json

*A few sentences describing the overall effects and goals of the pull request's commits.*
on celo.org homepage platform stats widget remove "wallet" from wallet addresses so that its just "Addresses"
**What is the current behavior, and what is the updated/expected behavior with this PR?**
*Before*
*After*
**Tested**
Related issues
Fixes #148

changed the statsAddressess to just have addresses

---

public/static/locales/en/faucet.json
src/_page-tests/developers/__snapshots__/faucet.test.tsx.snap

Adds cEUR to the text for the `/developers/faucet` page.

Update faucet page wording to include cEUR

---

next.config.js
src/_page-tests/__snapshots__/about.test.tsx.snap
src/shared/VideoModal.tsx

bundle size: before *86k* now *17k*
lighthouse: 72 =91 perf 
* Next.js has an option to inline images base64 style. this however means they end up in the javascript code. I changed the threashold so that only images less than 1k will be included, which i think is a good compromise between reducing number of requests vs reducing bundles. 60k of the reduction on about page came from this
* LazyLoading components. About Page has A modal which plays a youtube video the ReactModal and YouTube components that do this added about 10k. these are now lazyloaded. 
the inline image change also reduce bundle for other pages

Bundle Size Reduction

---

src/home/stats/useStatsRelay.ts

sometimes average block time would report a wrong number that was like total addresses. 
fixed by returned state so we dont fall thru the case switch

fixes addresses being assigned to block time sometimes

---

public/static/locales/en/home.json
src/_page-tests/__snapshots__/index.test.tsx.snap
src/_page-tests/developers/__snapshots__/Index.test.tsx.snap
src/contentful/nodes/nodes.tsx
src/shared/menu-items.ts

update text of link
fix deadline
fix images in kits.
Trick was to get images that were both natively bigger and natively smaller than the window to show up nicely.
before
after
#188 
#183

A few updates and fixes

---

public/locales/en/celoRewards.json
public/locales/es/celoRewards.json
public/locales/pt/celoRewards.json
public/locales/tl/celoRewards.json
src/celo-rewards/CeloRewardsTerms.tsx

Added banner communicating end of CELO rewards:

Add banner communicating end of CELO rewards

---

src/contentful/grid2-cells/FreeContent.tsx
src/home/Cover.tsx
src/public-sector/FreeContent.tsx

We want to have h1 styles, but only have one h1 tag on the home page for accessibility reasons. 
For some reason, it wasn't working correctly when I just wanted to use the fonts.h1 style, so I had to create a new style in this page, and it worked.
Mobile styles are included, and uses the same styles as the h1 font. 
I know this is a duplication of some code, but when using imported css styles of fonts.h1, i got something like this: 
Screenshot below of using styles defined in the page:

Render a h2 with an h1 style for the home page 

---

pages/use-a-dapp.tsx
pages/v6/[slug].tsx
src/_page-tests/__snapshots__/index.test.tsx.snap
src/_page-tests/index.test.tsx
src/contentful/Cover.tsx
src/contentful/HorizontalRule.tsx
src/contentful/grid2-cells/FreeContent.tsx
src/contentful/grid2-cells/Heading.tsx
src/contentful/nodes/enodes.tsx
src/home/Cover.tsx
src/home/cellSwitch.tsx
src/public-sector/CommonContentFullPage.tsx
src/public-sector/cellSwitch.tsx
src/utils/contentful.ts

- create a new nodeRenderer for regular h* tags instead of using the RNW version
- let cover subtitle be many different styles
- add optional superSize for the title on cover (used posthaste on the public sector page, since it bigger than h1) 
- remove unused dynamic imports 
- home page cover add padding to top
- add a `HR` component for between grid sections

tuesday changes

---

src/plumo/Rounds.tsx

Fixes Bug in safari where row heights are too high. oddly setting the container of the grid to be a grid itself fixes this.

fix safari row height bug

---

src/contentful/Cover.tsx

fix issue on tablet where math caused image padding and size to be 100000% of width and thus very stretched

fix cover tablet stretching

---

src/header/Navigation.tsx

Includes "asPath" from useRouter to match Ecosystem page in the nav bar 
fixes #487

Fix green coin not showing on Ecosystem in Navigation 

---

src/header/Navigation.tsx

Parentheses was needed, otherwise only showed up for the Ecosystem page

Fix Oval Coin 

---

pages/experience/brand/key-imagery.tsx
public/locales/en/brand.json
src/_page-tests/experience/__snapshots__/color.test.tsx.snap
src/_page-tests/experience/__snapshots__/composition.test.tsx.snap
src/_page-tests/experience/__snapshots__/exchange-icons.test.tsx.snap
src/_page-tests/experience/__snapshots__/icons.test.tsx.snap
src/_page-tests/experience/__snapshots__/index.test.tsx.snap
src/_page-tests/experience/__snapshots__/key-imagery.test.tsx.snap
src/_page-tests/experience/__snapshots__/logo.test.tsx.snap
src/_page-tests/experience/__snapshots__/typography.test.tsx.snap
src/_page-tests/experience/key-imagery.test.tsx
src/experience/brandkit/KeyImagery.tsx
src/experience/brandkit/common/Page.tsx

Most edits come from Airtable, we basically move assets into Illustrations from Abstract Graphics, as well as delete the subheaders in the nav.

Make edits on BrandKit for Key Imagery page 

---

server/index.ts

Redirected the link from "celo.org/celo-connect2022" to "celoconnect.com".
issue #587

redirected the site

---

server/index.ts

The Supercharge program has changed and is no longer funded by Community Funds, so we're moving (and updating) the T&C to Valora's website

Add redirect to Valora's Supercharge T&C

---

public/locales/en/faucet.json
src/_page-tests/developers/__snapshots__/faucet.test.tsx.snap

There is a limit to the number of tokens we can faucet. So faucet less per time.

fix: Number of tokens we say are fauceted

---

pages/api/ecosystem/[form].ts
server/addToCRM.ts

A missing Return Statement was causing the form to error out (after it had submitted the contact to hubspot but not before linking it to company)
also lets log errors

fix missing return statement
