celo-org/website

src/home/stats/Stats.tsx, src/home/stats/useStatsRelay.ts
Fixes trying to call `replace` on `undefined` issue
plus some magic
=> fix white blank page when replace function failed

src/_page-tests/developers/__snapshots__/Index.test.tsx.snap, src/_page-tests/validators/__snapshots__/index.test.tsx.snap, src/dev/Cover.tsx, src/dev/Engage.tsx
Validator page is currently broken on mobile.
=> fix broken images on validator page when on a small screen

.gcloudignore, next.config.js
`modern true` causes next to output too many files for GCP to work over 1000
also dont upload some files to GCP
=> Fix deploying

next.config.js
Added React Strict Mode to the root of the App.
=> Added React Strict Mode to App

pages/_document.tsx, src/analytics/analytics.ts
adds a tracking for active campaign  which only runs if visitors have opted in. 
Fixes #117
=> add active campaign code

package.json, yarn.lock
accidentally had this in prod builds
=> remove analyzer

src/contentful/grid2-cells/Roledex.tsx
Design calls for dropdown to be used on mobile for our rolodex sheet selection 
also links in this section should be left aligned
=> add dropdown on mobile for roledex

src/header/BlueBanner.tsx, src/header/Navigation.tsx, src/header/__snapshots__/Navigation.test.tsx.snap
fixes issue with top nav being on top of blue banner when navigating from another page to home page. This was due to 
1. toggleing the state rather than setting it based on announcement visibility
2. using componentDidUpdate rather than an explict useLayoutEffect with route as a dep
also make it a little quicker 
fixes #153
=> Fixes Navigation Bar Bug

pages/api/alliance.ts, pages/api/blog.ts, pages/api/carbon.ts, pages/api/contributors.ts, server/byMethod.ts
res.status can lead to timeouts. add json so something is returned.
tested on staging.
=> Fix high latency errors

src/_page-tests/experience/__snapshots__/typography.test.tsx.snap, src/header/__snapshots__/Navigation.test.tsx.snap, src/shared/Footer.tsx, src/shared/__snapshots__/MobileMenu.test.tsx.snap, src/shared/menu-items.ts
New nav links
Figma: https://www.figma.com/file/E7HhqLi5TrFwcCpKriqEu4/Celo-Website-5.0?node-id=43%3A0
=> Top Nav changes

public/locales/en/home.json, src/home/stats/CarbonStats.tsx, src/home/stats/Stats.tsx, src/home/stats/useStatsRelay.ts
Simplifies the stats displayed on celo.org 
- no longer showing addresses or blockcount
- show carbon neutral days
=> Change Displayed Stats

pages/index.tsx, src/home/Home.tsx
Adds "true" to getPagebySlug function to pull in home content 
Styles will be updated in Contentful (going to add a maxWidth for the text section above the trio)
=> Pull in home page content 

server/addToCRM.ts, src/shared/Footer.tsx
typo ment this was not actually working.
=> fix email form

src/plumo/Rounds.tsx, src/plumo/usePhase.ts
fix issue with hooks and effects causing bugs with round selection
also dont log "error" string if there is not error. cause it looks like something broke
=> fix issue with hooks and effects causing bugs with round selection

src/contentful/LogoGallary.tsx, src/contentful/nodes/embeds/GALLARY.tsx, src/utils/contentful.ts
Adds cssStyle prop to LogoGallery, removes maxWidth property
idea is to pass in marginleft: 0px, and marginRight: 0px for the <a> component in Contentful https://app.contentful.com/spaces/bzlah72jow8z/entries/4gJ4g7Hkkypmm7HbFKf7Yh
=> Add custom css to logo gallery WIP

development.yaml, production.yaml, server/index.ts, src/_page-tests/__snapshots__/plumo.test.tsx.snap, src/_page-tests/experience/__snapshots__/color.test.tsx.snap, src/_page-tests/experience/__snapshots__/composition.test.tsx.snap, src/_page-tests/experience/__snapshots__/exchange-icons.test.tsx.snap, src/_page-tests/experience/__snapshots__/icons.test.tsx.snap, src/_page-tests/experience/__snapshots__/index.test.tsx.snap, src/_page-tests/experience/__snapshots__/key-imagery.test.tsx.snap, src/_page-tests/experience/__snapshots__/logo.test.tsx.snap, src/_page-tests/experience/__snapshots__/typography.test.tsx.snap, src/shared/Footer.tsx, src/shared/__snapshots__/Footer.test.tsx.snap, staging.yaml
This updates the links to the annual report to a static file in our /public folder.
Some formatting changes
=> Add annual report 2020 to public folder, update links 

public/locales/en/about.json, public/locales/en/common.json, public/locales/en/home.json, src/_page-tests/__snapshots__/about.test.tsx.snap, src/_page-tests/__snapshots__/index.test.tsx.snap, src/press/Press.tsx, src/shared/Footer.tsx, src/shared/__snapshots__/Footer.test.tsx.snap
a) remove that link: Contact Press
b) Capitalize on the platform stats
c) https://dev.celo.org/about#backers CHANGE text
Bonus; remove unused translations
=> Website 5.0.1

src/public-sector/Picture.tsx
=> fix completely messed up syntax for 2x images

next.config.js
This set a default caching of 45 seconds for all pages and page resources.
=> add basic caching of 45 seconds

pages/press.tsx, src/press/PressPage.tsx
1. - use optional `?.` to avoid error when there are no accept lang headers 
2. - fix typo in formated
3. - memoize the expensive creating of set and filtering
4. use Function not class for component
=> Press page minor improvements

src/_page-tests/__snapshots__/plumo.test.tsx.snap, src/_page-tests/experience/__snapshots__/color.test.tsx.snap, src/_page-tests/experience/__snapshots__/composition.test.tsx.snap, src/_page-tests/experience/__snapshots__/exchange-icons.test.tsx.snap, src/_page-tests/experience/__snapshots__/icons.test.tsx.snap, src/_page-tests/experience/__snapshots__/index.test.tsx.snap, src/_page-tests/experience/__snapshots__/key-imagery.test.tsx.snap, src/_page-tests/experience/__snapshots__/logo.test.tsx.snap, src/_page-tests/experience/__snapshots__/typography.test.tsx.snap, src/estyles.tsx, src/forms/EmailForm.tsx, src/layout/Grid2.tsx, src/shared/ChangeStory.tsx, src/shared/Footer.tsx, src/shared/__snapshots__/Footer.test.tsx.snap
Remove React native web/styles from Footer and ChangeStory.![Screen Shot 2021-08-02 at 11 21 34 AM](https://user-images.githubusercontent.com/3814795/127927459-9863eadf-a33b-48e1-bd06-104f6e1ca3f2.png)
add `Cell` component for 
* some prettification  and spelling fixes
=> [RNWR] Refactor Footer and ChangeStory components

src/_page-tests/__snapshots__/privacy.test.tsx.snap, src/_page-tests/developers/__snapshots__/faucet.test.tsx.snap, src/dev/FaucetPage.tsx, src/privacy/Privacy.tsx, src/terms/BrandPolicy.tsx
Work in progress, changing the usage of View components
=> Removing View component from multiple pages in celo.org 

src/_page-tests/__snapshots__/plumo.test.tsx.snap, src/_page-tests/experience/__snapshots__/color.test.tsx.snap, src/_page-tests/experience/__snapshots__/composition.test.tsx.snap, src/_page-tests/experience/__snapshots__/exchange-icons.test.tsx.snap, src/_page-tests/experience/__snapshots__/icons.test.tsx.snap, src/_page-tests/experience/__snapshots__/index.test.tsx.snap, src/_page-tests/experience/__snapshots__/key-imagery.test.tsx.snap, src/_page-tests/experience/__snapshots__/logo.test.tsx.snap, src/_page-tests/experience/__snapshots__/typography.test.tsx.snap, src/header/__snapshots__/Navigation.test.tsx.snap, src/shared/__snapshots__/Footer.test.tsx.snap, src/shared/__snapshots__/MobileMenu.test.tsx.snap, src/shared/menu-items.ts
*Description*
Added the "Public-Sector" tab to the navbar 
Issue #341
=> added public sector to the main page

src/_page-tests/__snapshots__/index.test.tsx.snap, src/press/Press.tsx
=> Fixes gradient to match dark color on Home Page 

pages/api/enterprise.ts, server/EnterpriseContacts.ts, server/addToCRM.ts
=> add enterprise form, fix race condition on list

package.json, src/_page-tests/__snapshots__/plumo.test.tsx.snap, src/_page-tests/experience/__snapshots__/color.test.tsx.snap, src/_page-tests/experience/__snapshots__/composition.test.tsx.snap, src/_page-tests/experience/__snapshots__/exchange-icons.test.tsx.snap, src/_page-tests/experience/__snapshots__/icons.test.tsx.snap, src/_page-tests/experience/__snapshots__/index.test.tsx.snap, src/_page-tests/experience/__snapshots__/key-imagery.test.tsx.snap, src/_page-tests/experience/__snapshots__/logo.test.tsx.snap, src/_page-tests/experience/__snapshots__/typography.test.tsx.snap, src/shared/__snapshots__/Footer.test.tsx.snap, yarn.lock
Updates to latest 
* emotion/react
* contentful/rich-text-react-renderer
* lottie-web
=> Jan 2022 Upgrades 

src/_page-tests/__snapshots__/index.test.tsx.snap, src/press/Press.tsx
=> Comment out hackathon banner for now 

server/addToCRM.ts
If we always pass in first and last name then it overwrites the existing data.
=> dont overwrite keys

next.config.js, src/experience/brandkit/KeyImagery.tsx, src/experience/common/Showcase.tsx, src/experience/common/ShowcaseKeyImagery.tsx, src/experience/common/constants.tsx
PR for fixing up key imagery 
Figma: https://www.figma.com/file/sJM2FyUcqNucwrCgXRHJbw/Celo-BrandKit-1.5?node-id=1025%3A2968
=> Key Imagery Edits 

.vscode/settings.json, src/_page-tests/__snapshots__/index.test.tsx.snap, src/contentful/grid2-cells/Editorial.tsx, src/contentful/grid2-cells/FreeContent.tsx, src/home/Cover.tsx, src/hooks/useInternval.ts, src/public-sector/cellSwitch.tsx, src/utils/contentful.ts
* Adds fun animation of marquee
* adds new Editorial Component/Type 
* adds ability to specify number of rows free content area spans. 
https://user-images.githubusercontent.com/3814795/151454250-85fa3928-d04f-43f3-8314-f6d7b91bc657.mov
=> Cover + Editorial section

src/_page-tests/__snapshots__/index.test.tsx.snap, src/home/Cover.tsx, src/home/stats/Stats.tsx
align cover and stats widget in it to look nice at tablet to desktop 
https://user-images.githubusercontent.com/3814795/151606302-ee0f5cc7-1a1a-427b-87af-e75f3c82f378.mov
to large desktop views.
=> cover align mint

src/_page-tests/__snapshots__/index.test.tsx.snap, src/home/Timeline.tsx, src/public-sector/cellSwitch.tsx, src/utils/contentful.ts
=> Add Timeline components for green climate

public/locales/en/home.json, src/_page-tests/index.test.tsx, src/home/Cover.tsx, src/home/Home.tsx, src/home/stats/Stats.tsx
=> switch from cover style to just a simple heading and light mode stats

src/cico/CicoPage.tsx
A text box inserted to be used a search bar
=> created a search bar

server/index.ts
Updated and added the annual report for 2021. Also there was a bug on the annual report for 2020 which also has been updated and fixed.
=> updated the annual report 2021

src/_page-tests/__snapshots__/plumo.test.tsx.snap, src/_page-tests/experience/__snapshots__/color.test.tsx.snap, src/_page-tests/experience/__snapshots__/composition.test.tsx.snap, src/_page-tests/experience/__snapshots__/exchange-icons.test.tsx.snap, src/_page-tests/experience/__snapshots__/icons.test.tsx.snap, src/_page-tests/experience/__snapshots__/index.test.tsx.snap, src/_page-tests/experience/__snapshots__/key-imagery.test.tsx.snap, src/_page-tests/experience/__snapshots__/logo.test.tsx.snap, src/_page-tests/experience/__snapshots__/typography.test.tsx.snap, src/shared/Footer.tsx, src/shared/__snapshots__/Footer.test.tsx.snap
There was an error on the annual report. Just updated the latest version of the document. Also changed the redirection for the "Annual Report" link on the footer.
=> updated the annual report
